import type { Metadata } from "next";
import { iniriaSerif, meowScript, hortensia } from "@/app/ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="es" className={`${iniriaSerif.variable} ${meowScript.variable} ${hortensia.variable}`} >
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body className="font-iniria-serif font-normal antialiased">{children}</body>
    </html>
  );
}
